[workspace]
members = [
    "contracts/cw20-token",
    "contracts/staking",
    "packages/shared",
]
resolver = "2"

[workspace.dependencies]
cosmwasm-std = "1.5.0"
cosmwasm-schema = "1.5.0"
cw-storage-plus = "1.2.0"
cw20 = "1.1.0"
cw-ownable = "0.3.0"
cw-multi-test = "0.16.0"
schemars = "0.8.12"
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.50"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true