[workspace]
members = [
    "contracts/cw20-token",
    "contracts/staking",
    "packages/shared",
]

resolver = "2"

[workspace.dependencies]
cosmwasm-std = "3.0"
cosmwasm-schema = "3.0"
cw-storage-plus = "3.0"
cw20 = { version = "2.0.0-rc.0" }
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true