[package]
name = "cw20-token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
cw-storage-plus.workspace = true
cw20.workspace = true
cw-ownable.workspace = true
schemars.workspace = true
serde.workspace = true
thiserror.workspace = true
ed25519-zebra = { version = "4.1", features = ["alloc"] }  # ← напрямую

shared = { path = "../../packages/shared" }

[dev-dependencies]
cw-multi-test.workspace = true