[package]
name = "staking"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std.workspace = true
cosmwasm-schema.workspace = true
cw-ownable.workspace = true
cw-storage-plus.workspace = true
cw20.workspace = true
schemars.workspace = true
serde.workspace = true
thiserror.workspace = true
cw20-token = { path = "../cw20-token" }
ed25519-zebra = { version = "4.1", features = ["alloc"] }  # ← напрямую

[dev-dependencies]
cosmwasm-std.workspace = true
cw-multi-test.workspace = true